import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/auth";
import { SonarProvider, Toaster } from "@/components/ui/sonar";
import Script from 'next/script'

const interTight = Inter_Tight({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <Script
        defer
        src='https://cloud.umami.is/script.js'
        data-website-id='f7f79308-10ce-4c1f-8662-18dc4dab029d'
      />
      <body
        className={`${interTight.className} antialiased`}
        suppressHydrationWarning
      >
        <AuthProvider>
            <SonarProvider>
              {children}
              <Toaster
                position="top-center"
                duration={5000}
              />
            </SonarProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
