import type { Metadata } from "next";
import { GitHubLogoIcon } from "@radix-ui/react-icons";
import { Inter_Tight } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import UserAuthButton from "@/components/auth/userbutton";

const interTight = Inter_Tight({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div className="relative mx-auto flex h-dvh w-full max-w-6xl flex-col px-6 md:px-8 lg:px-12">
      <header className="flex items-center justify-between py-8">
        <Link href="/">
          <span className="text-neutral-950">gnosei</span>
        </Link>
        <nav className="flex items-center gap-4">
          <Link href="https://github.com/michahl/gnosei" target="_blank">
            <GitHubLogoIcon className="h-6 w-6 text-neutral-800 transition-colors hover:text-neutral-600" />
          </Link>
          <UserAuthButton />
        </nav>
      </header>
      <main className="flex-1">{children}</main>
      <footer>
        <div className="flex items-center justify-center py-8">
          <span className="text-sm text-neutral-800">
            Made by
            <a
              href="https://github.com/michahl"
              target="_blank"
              rel="noopener noreferrer"
              className="ml-1 rounded-full bg-neutral-100 px-2 py-1 text-neutral-950"
            >
              @michahl
            </a>
          </span>
        </div>
      </footer>
    </div>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interTight.className} antialiased`}
        suppressHydrationWarning
      >
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  );
}
